image: opickford/pr-delta-comment:latest

pipelines:
  pull-requests:
    # Define the branch where you want to add the comment
    '**':
      - step:
          # The python app can be invoked using the script command below
          name: Snyk delta scan & PR comment
          script:
            - snyk-pr-delta-comment
